/* =============================================================
   build_allowlist.js

   Writes the server's list of valid rows into Code.gs, generated from
   assets/js/config.js so the two cannot drift apart.

   Code.gs refuses any row whose key is not on this list, and writes the
   rack and rating from here rather than from the request - so a stranger
   holding the public URL cannot invent equipment, and cannot lie about a
   breaker's rating to change the "% loaded" the sheet shows.

   RUN THIS AFTER EVERY EDIT TO config.js THAT ADDS, REMOVES OR RENAMES A
   FEEDER OR A PDU WAY, then paste Code.gs into Apps Script and deploy a
   New version. If you forget, the server refuses the new way's readings
   with a message naming it - a safe failure, not a silent one.

       node apps-script/build_allowlist.js

   The key and rating rules below mirror load-reading.js exactly (keyOf,
   ratedFromBreaker). test_hardening.js checks that they still agree.
   ============================================================= */

'use strict';

const fs     = require('fs');
const path   = require('path');
const vm     = require('vm');
const crypto = require('crypto');

const ROOT    = path.resolve(__dirname, '..');
const CONFIG  = path.join(ROOT, 'assets', 'js', 'config.js');
const CODE_GS = path.join(__dirname, 'Code.gs');

const BEGIN = '/* @@ALLOWLIST-BEGIN - generated by build_allowlist.js, do not edit by hand */';
const END   = '/* @@ALLOWLIST-END */';

/* The line the fingerprint lives on. It is blanked before hashing, so the
   hash never depends on the value it is about to be replaced with. */
const FP_LINE = /var CODE_FINGERPRINT = '[^']*';/;

/* A hash of the whole of Code.gs, so it changes on any edit at all.
   Line endings are normalised first: git turns LF into CRLF on this machine,
   and the same file must give the same fingerprint wherever it came from. */
function fingerprint(text) {
    const norm = text.replace(/\r\n?/g, '\n').replace(FP_LINE, "var CODE_FINGERPRINT = '';");
    return crypto.createHash('sha1').update(norm, 'utf8').digest('hex').slice(0, 12);
}

/* The value currently written in the file, or null if there is none. */
function stampedIn(text) {
    const m = /var CODE_FINGERPRINT = '([^']*)';/.exec(text);
    return m ? m[1] : null;
}

/* config.js is browser code: it touches location, localStorage and
   history at the bottom. Give it just enough of a window to load. */
function loadConfig() {
    const sandbox = {
        location: { search: '', pathname: '/', hash: '' },
        history:  { replaceState() {} },
        localStorage: { getItem() { return null; }, setItem() {}, removeItem() {} },
        atob: (s) => Buffer.from(s, 'base64').toString('binary'),
        console
    };
    vm.createContext(sandbox);
    vm.runInContext(fs.readFileSync(CONFIG, 'utf8') + '\n;this.DC_CONFIG = DC_CONFIG;', sandbox);
    return sandbox.DC_CONFIG;
}

/* identical to load-reading.js */
function keyOf(category, equipment, circuit) {
    return [category, equipment, circuit || ''].join('|');
}
function ratedFromBreaker(s) {
    if (!s) return null;
    const m = String(s).match(/(\d+(?:\.\d+)?)/);
    return m ? parseFloat(m[1]) : null;
}

function build(cfg) {
    const out = {};
    cfg.equipment.forEach(e => {
        out[keyOf('Main', e.name, '')] = { rack: '', rated: e.rated == null ? '' : e.rated };
    });
    Object.keys(cfg.pduCircuits).forEach(pdu => {
        cfg.pduCircuits[pdu].forEach(c => {
            const r = ratedFromBreaker(c.breaker);
            out[keyOf('PDU', pdu, c.c)] = { rack: c.rack || '', rated: r == null ? '' : r };
        });
    });
    return out;
}

function render(list) {
    const keys = Object.keys(list);
    /* One line per row, as [rack, rated]. Compact, and a diff of it reads
       as a diff of the equipment. */
    const lines = keys.map(k =>
        '  ' + JSON.stringify(k) + ': ' + JSON.stringify([list[k].rack, list[k].rated]));
    return [
        BEGIN,
        '/* ' + keys.length + ' rows. key -> [rack, rated A]. Source: assets/js/config.js */',
        'var ALLOWED = {',
        lines.join(',\n'),
        '};',
        END
    ].join('\n');
}

function main() {
    const cfg  = loadConfig();
    const list = build(cfg);
    const block = render(list);

    let gs = fs.readFileSync(CODE_GS, 'utf8');
    const a = gs.indexOf(BEGIN), b = gs.indexOf(END);
    if (a === -1 || b === -1) {
        throw new Error('Allowlist markers not found in Code.gs');
    }
    gs = gs.slice(0, a) + block + gs.slice(b + END.length);

    /* Stamp last, over the finished file, so the fingerprint covers the
       allowlist just written as well as everything else. */
    if (!FP_LINE.test(gs)) throw new Error('CODE_FINGERPRINT line not found in Code.gs');
    const fp = fingerprint(gs);
    gs = gs.replace(FP_LINE, "var CODE_FINGERPRINT = '" + fp + "';");
    fs.writeFileSync(CODE_GS, gs);

    const main = Object.keys(list).filter(k => k.indexOf('Main|') === 0).length;
    console.log('Code.gs allowlist written: ' + Object.keys(list).length + ' rows (' +
                main + ' main, ' + (Object.keys(list).length - main) + ' PDU ways)');
    console.log('Code.gs fingerprint:       ' + fp);
}

if (require.main === module) main();
module.exports = { loadConfig, build, keyOf, ratedFromBreaker, fingerprint, stampedIn, CODE_GS };
