/**
 * KOC Data Center - Load Reading
 * Google Apps Script web app behind load-reading.html.
 *
 * Readings are submitted a feeder at a time, because the equipment sits in
 * different areas and is read at different times. Each feeder becomes one row.
 *
 * Two request types, both POST:
 *
 *   { type: 'status', date: '2026-09-06' }
 *       -> what is already recorded for that date, so the page can show
 *          "Already Recorded" instead of letting someone enter it twice.
 *
 *   { type: 'load-reading', meta: {...}, rows: [ {...}, ... ] }
 *       -> save. Any row already present for that date is refused as a
 *          duplicate unless it carries replace:true, which overwrites the
 *          existing row in place rather than appending a correction.
 *
 * -------------------------------------------------------------------------
 * SETUP
 *   1. Open the target Google Sheet, Extensions > Apps Script.
 *   2. Paste this file over Code.gs and save.
 *   3. Deploy > New deployment > type "Web app".
 *        Execute as:        Me
 *        Who has access:    Anyone
 *      "Anyone" is required - the page posts without a Google sign-in.
 *   4. Copy the /exec URL into DC_CONFIG.endpoint in assets/js/config.js.
 *
 * THE URL IS PUBLIC
 *   It is built into a page served from a public repository, and the
 *   deployment must accept "Anyone", so this script has to assume a stranger
 *   can post to it. It therefore trusts nothing in a request:
 *
 *     - only the three request types above do anything;
 *     - a row is written only if its key is on ALLOWED, the list of real
 *       feeders and PDU ways generated from config.js;
 *     - the rack and the rating are written from ALLOWED, never from the
 *       request, and Max A, % loaded and Unbalance % are recomputed here;
 *     - currents must be numbers between 0 and MAX_AMPS;
 *     - free text is length-capped and cannot start a formula, so nothing a
 *       request sends can make the sheet fetch or run anything;
 *     - every overwrite is copied to the Audit tab first, with what it
 *       replaced, so a false reading written over a real one is visible and
 *       reversible.
 *
 *   What this does NOT stop: someone holding the URL writing a plausible
 *   false reading for a real feeder. Only a per-person token checked here
 *   would stop that. The Audit tab is what makes it detectable meanwhile.
 *
 * AFTER EDITING config.js
 *   If a feeder or PDU way was added, removed or renamed, run
 *       node apps-script/build_allowlist.js
 *   to regenerate ALLOWED, then paste this file and deploy a New version.
 *   Until then the server refuses that row by name - it does not guess.
 *
 * AFTER ANY EDIT TO THIS FILE
 *   Deploy > Manage deployments > edit > Version: **New version** > Deploy.
 *   Saving alone does not update the published web app: the old code keeps
 *   running and the change fails silently.
 * -------------------------------------------------------------------------
 */

/** Tab the readings are written to. Created automatically if absent. */
var SHEET_NAME = 'Load Readings';

/** Column order. The header row is written once, on first use. */
var HEADERS = [
  'Timestamp', 'Date', 'Time', 'Taken by', 'Site',
  'Category', 'Equipment', 'Circuit', 'Rack', 'Rated A',
  'R', 'Y', 'B', 'Max A', '% loaded', 'Unbalance %', 'Remarks'
];

/* Column positions, 1-based, so the offsets below stay readable. */
var C_DATE = 2, C_CATEGORY = 6, C_EQUIPMENT = 7, C_CIRCUIT = 8;
var C_R = 11, C_Y = 12, C_B = 13;

/** Where overwritten rows are copied before they are replaced. */
var AUDIT_SHEET = 'Audit';

/* What a request may contain. Generous enough never to refuse a real round -
   a full round is about 300 rows, the largest device is a 2133 A incomer and
   the busbar is 3200 A - and tight enough to refuse junk.

   MAX_AMPS is deliberately NOT tied to each feeder's rating. A reading above
   rating is an overload, which is exactly the reading this sheet exists to
   capture; refusing it would hide the one finding that matters. The ceiling
   only rejects numbers no clamp meter on this site could produce. */
var LIMITS = {
  MAX_ROWS:   700,
  MAX_AMPS:   5000,
  MAX_TEXT:   120,
  FIRST_YEAR: 2015,        /* the sheet's earliest reading is 2023 */
  DAYS_AHEAD: 2            /* a reading cannot be dated far in the future */
};

/* @@ALLOWLIST-BEGIN - generated by build_allowlist.js, do not edit by hand */
/* 590 rows. key -> [rack, rated A]. Source: assets/js/config.js */
var ALLOWED = {
  "Main|Incomer A|": ["",2133],
  "Main|Incomer B|": ["",2133],
  "Main|EMSB 1|": ["",1000],
  "Main|EMSB 4|": ["",400],
  "Main|EDB 27|": ["",125],
  "Main|Battery Charger & Fuel Pump|": ["",125],
  "Main|EMSB 9|": ["",630],
  "Main|EMSB 3|": ["",400],
  "Main|MSB 10|": ["",630],
  "Main|MSB 8|": ["",400],
  "Main|MCC 2|": ["",800],
  "Main|MSB 7|": ["",250],
  "Main|DB 2|": ["",125],
  "Main|ATS 002|": ["",2000],
  "Main|PDU 1|": ["",160],
  "Main|PDU 3|": ["",160],
  "Main|PDU 5|": ["",160],
  "Main|PDU 7|": ["",160],
  "Main|PDU 6|": ["",160],
  "Main|PDU 2|": ["",160],
  "Main|PDU 4|": ["",160],
  "Main|PDU 8|": ["",160],
  "Main|EDB 28|": ["",40],
  "Main|Generator Control Panel|": ["",125],
  "Main|EMSB 2|": ["",1000],
  "Main|EMCC 1|": ["",800],
  "PDU|PDU 1|Q1": ["Cabin A-01",20],
  "PDU|PDU 1|Q2": ["Cabin A-02",20],
  "PDU|PDU 1|Q3": ["Cabin A-03",20],
  "PDU|PDU 1|Q4": ["Cabin A-04",20],
  "PDU|PDU 1|Q5": ["SPARE",20],
  "PDU|PDU 1|Q6": ["SPARE",20],
  "PDU|PDU 1|Q7": ["Cabin A-07",25],
  "PDU|PDU 1|Q8": ["Cabin A-08",25],
  "PDU|PDU 1|Q9": ["Cabin A-08",25],
  "PDU|PDU 1|Q10": ["Cabin A-09",25],
  "PDU|PDU 1|Q11": ["Cabin A-09",25],
  "PDU|PDU 1|Q12": ["Cabin A-10",25],
  "PDU|PDU 1|Q13": ["Cabin A-10",25],
  "PDU|PDU 1|Q14": ["Cabin B-02",25],
  "PDU|PDU 1|Q15": ["Cabin B-02",25],
  "PDU|PDU 1|Q16": ["Cabin B-03",25],
  "PDU|PDU 1|Q17": ["Cabin B-03",25],
  "PDU|PDU 1|Q18": ["Cabin B-04",32],
  "PDU|PDU 1|Q19": ["SPARE",32],
  "PDU|PDU 1|Q20": ["Cabin B-06",32],
  "PDU|PDU 1|Q21": ["Cabin B-07",32],
  "PDU|PDU 1|Q22": ["Cabin B-09",25],
  "PDU|PDU 1|Q23": ["Cabin B-09",25],
  "PDU|PDU 1|Q24": ["Cabin B-05",32],
  "PDU|PDU 1|Q25": ["Cabin B-05",32],
  "PDU|PDU 1|Q26": ["SPARE Cabin A-14",32],
  "PDU|PDU 1|Q27": ["Cabin A-14",32],
  "PDU|PDU 1|Q28": ["SPARE",32],
  "PDU|PDU 1|Q29": ["SPARE",32],
  "PDU|PDU 1|Q30": ["SPARE",32],
  "PDU|PDU 1|Q31": ["SPARE",16],
  "PDU|PDU 1|Q32": ["SPARE",16],
  "PDU|PDU 1|Q33": ["SPARE",16],
  "PDU|PDU 1|Q34": ["SPARE",16],
  "PDU|PDU 1|Q35": ["SPARE",16],
  "PDU|PDU 1|Q36": ["SPARE",16],
  "PDU|PDU 1|Q37": ["SPARE",16],
  "PDU|PDU 1|Q38": ["SPARE",16],
  "PDU|PDU 1|Q39": ["SPARE",16],
  "PDU|PDU 1|Q40": ["SPARE",16],
  "PDU|PDU 1|Q41": ["SPARE",16],
  "PDU|PDU 1|Q42": ["SPARE",16],
  "PDU|PDU 1|Q43": ["Cabin K-05",25],
  "PDU|PDU 1|Q44": ["Cabin K-06",25],
  "PDU|PDU 1|Q45": ["Cabin K-06",25],
  "PDU|PDU 1|Q46": ["SPARE IND. SOCKET",25],
  "PDU|PDU 1|Q47": ["SPARE IND. SOCKET",25],
  "PDU|PDU 1|Q48": ["SPARE IND. SOCKET",25],
  "PDU|PDU 1|Q49": ["SPARE IND. SOCKET",25],
  "PDU|PDU 1|Q50": ["SPARE IND. SOCKET",25],
  "PDU|PDU 1|Q51": ["Cabin A05 SPARE",25],
  "PDU|PDU 1|Q52": ["Cabin A05",25],
  "PDU|PDU 1|Q53": ["Cabin A06",25],
  "PDU|PDU 1|Q54": ["Cabin A06",25],
  "PDU|PDU 1|Q55": ["SPARE",25],
  "PDU|PDU 1|Q56": ["SPARE",25],
  "PDU|PDU 1|Q57": ["SPARE",16],
  "PDU|PDU 1|Q58": ["SPARE",16],
  "PDU|PDU 1|Q59": ["SPARE",25],
  "PDU|PDU 1|Q60": ["SPARE",25],
  "PDU|PDU 1|Q61": ["SPARE",25],
  "PDU|PDU 1|Q62": ["SPARE",25],
  "PDU|PDU 1|Q63": ["A Building corridor near admin",25],
  "PDU|PDU 1|Q64": ["C Building LAN Room C-106",16],
  "PDU|PDU 1|Q65": ["A Building Telecom room wall socket",16],
  "PDU|PDU 1|Q66": ["B Building LAN Room ind. socket",16],
  "PDU|PDU 1|Q67": ["B Building LAN Room 13A socket",16],
  "PDU|PDU 1|Q68": ["A Building Telecom room wall socket",16],
  "PDU|PDU 1|Q69": ["A Building Room A14 wall socket",16],
  "PDU|PDU 1|Q70": ["A Building Room A14 floor socket",16],
  "PDU|PDU 1|Q71": ["A Building Room A14 floor socket",16],
  "PDU|PDU 1|Q72": ["A Building Room A14 floor socket",16],
  "PDU|PDU 1|Q73": ["A Building Room A14 floor socket",16],
  "PDU|PDU 1|Q74": ["Cabin A11",25],
  "PDU|PDU 1|Q75": ["RMS",16],
  "PDU|PDU 1|Q76": ["Cabin A12",25],
  "PDU|PDU 1|Q77": ["Cabin A13",16],
  "PDU|PDU 1|Q78": ["SPARE",16],
  "PDU|PDU 3|Q1": ["SPARE Cabin C-03",25],
  "PDU|PDU 3|Q2": ["SPARE Cabin C-03",25],
  "PDU|PDU 3|Q3": ["SPARE Cabin C-03",25],
  "PDU|PDU 3|Q4": ["Cabin C-04",25],
  "PDU|PDU 3|Q5": ["SPARE",25],
  "PDU|PDU 3|Q6": ["SPARE",25],
  "PDU|PDU 3|Q7": ["Cabin C-02",32],
  "PDU|PDU 3|Q8": ["Cabin C-05",32],
  "PDU|PDU 3|Q9": ["Cabin C-05",32],
  "PDU|PDU 3|Q10": ["Cabin C-07",25],
  "PDU|PDU 3|Q11": ["SPARE Cabin C-07",25],
  "PDU|PDU 3|Q12": ["Cabin C-08",25],
  "PDU|PDU 3|Q13": ["Cabin C-09",32],
  "PDU|PDU 3|Q14": ["Cabin C-09",32],
  "PDU|PDU 3|Q15": ["Cabin C-10",25],
  "PDU|PDU 3|Q16": ["Cabin C-11",16],
  "PDU|PDU 3|Q17": ["Cabin C-12",16],
  "PDU|PDU 3|Q18": ["Cabin D-02",25],
  "PDU|PDU 3|Q19": ["Cabin D-03",25],
  "PDU|PDU 3|Q20": ["Cabin D-04",25],
  "PDU|PDU 3|Q21": ["Cabin D-04",32],
  "PDU|PDU 3|Q22": ["Cabin D-05",25],
  "PDU|PDU 3|Q23": ["Cabin D-06",25],
  "PDU|PDU 3|Q24": ["Cabin D-06",25],
  "PDU|PDU 3|Q25": ["Cabin D-06A",25],
  "PDU|PDU 3|Q26": ["Cabin D-07",25],
  "PDU|PDU 3|Q27": ["Cabin D-08",25],
  "PDU|PDU 3|Q28": ["Cabin D-09",25],
  "PDU|PDU 3|Q29": ["Cabin D-10",25],
  "PDU|PDU 3|Q30": ["Cabin D-11",25],
  "PDU|PDU 3|Q31": ["Cabin D-11",25],
  "PDU|PDU 3|Q32": ["Cabin D-12",25],
  "PDU|PDU 3|Q33": ["Cabin D-12",25],
  "PDU|PDU 3|Q34": ["Cabin D-13",16],
  "PDU|PDU 3|Q35": ["Cabin D-14",16],
  "PDU|PDU 3|Q36": ["Cabin E-01",32],
  "PDU|PDU 3|Q37": ["Cabin E-06",32],
  "PDU|PDU 3|Q38": ["Cabin E-07",25],
  "PDU|PDU 3|Q39": ["Cabin E-09",16],
  "PDU|PDU 3|Q40": ["Cabin E-10",16],
  "PDU|PDU 3|Q41": ["Cabin E-11",16],
  "PDU|PDU 3|Q42": ["SPARE Cabin E-12",16],
  "PDU|PDU 3|Q43": ["SPARE",16],
  "PDU|PDU 3|Q44": ["SPARE IND. SOCKET",25],
  "PDU|PDU 3|Q45": ["SPARE IND. SOCKET",25],
  "PDU|PDU 3|Q46": ["SPARE IND. SOCKET",25],
  "PDU|PDU 3|Q47": ["SPARE IND. SOCKET",25],
  "PDU|PDU 3|Q48": ["SPARE IND. SOCKET",25],
  "PDU|PDU 3|Q49": ["Cabin C-13",25],
  "PDU|PDU 3|Q50": ["Cabin C-14",25],
  "PDU|PDU 3|Q51": ["Cabin B-10",32],
  "PDU|PDU 3|Q52": ["Cabin B-11",32],
  "PDU|PDU 3|Q53": ["Cabin B-12",32],
  "PDU|PDU 3|Q54": ["Cabin B-13",32],
  "PDU|PDU 3|Q55": ["Cabin B-14",32],
  "PDU|PDU 3|Q56": ["SPARE",32],
  "PDU|PDU 3|Q57": ["SPARE",32],
  "PDU|PDU 3|Q58": ["SPARE",32],
  "PDU|PDU 3|Q59": ["SPARE",16],
  "PDU|PDU 3|Q60": ["SPARE",25],
  "PDU|PDU 3|Q61": ["SPARE",25],
  "PDU|PDU 3|Q62": ["SPARE",16],
  "PDU|PDU 3|Q63": ["SPARE",25],
  "PDU|PDU 3|Q64": ["Cabin E-13",32],
  "PDU|PDU 3|Q65": ["SPARE",16],
  "PDU|PDU 3|Q66": ["SPARE",16],
  "PDU|PDU 3|Q67": ["SPARE",16],
  "PDU|PDU 3|Q68": ["SPARE",16],
  "PDU|PDU 3|Q69": ["SPARE",16],
  "PDU|PDU 3|Q70": ["SPARE",16],
  "PDU|PDU 3|Q71": ["SPARE",16],
  "PDU|PDU 3|Q72": ["SPARE",16],
  "PDU|PDU 3|Q73": ["SPARE",16],
  "PDU|PDU 3|Q74": ["SPARE",16],
  "PDU|PDU 3|Q75": ["SPARE",16],
  "PDU|PDU 3|Q76": ["SPARE",16],
  "PDU|PDU 3|Q77": ["SPARE",16],
  "PDU|PDU 3|Q78": ["SPARE",16],
  "PDU|PDU 5|Q1": ["SPARE",20],
  "PDU|PDU 5|Q2": ["SPARE",20],
  "PDU|PDU 5|Q3": ["SPARE",20],
  "PDU|PDU 5|Q4": ["SPARE",20],
  "PDU|PDU 5|Q5": ["Cabin H-12",25],
  "PDU|PDU 5|Q6": ["SPARE",20],
  "PDU|PDU 5|Q7": ["Cabin F-01",16],
  "PDU|PDU 5|Q8": ["SPARE Cabin F-01",16],
  "PDU|PDU 5|Q9": ["Cabin F-02",16],
  "PDU|PDU 5|Q10": ["Cabin F-03",16],
  "PDU|PDU 5|Q11": ["Cabin F-04",16],
  "PDU|PDU 5|Q12": ["Cabin F-05",16],
  "PDU|PDU 5|Q13": ["Cabin F-06",16],
  "PDU|PDU 5|Q14": ["Cabin F-03",16],
  "PDU|PDU 5|Q15": ["Cabin F-07",16],
  "PDU|PDU 5|Q16": ["Cabin F-09",16],
  "PDU|PDU 5|Q17": ["Cabin G-01",16],
  "PDU|PDU 5|Q18": ["Cabin G-02",16],
  "PDU|PDU 5|Q19": ["Cabin G-03",16],
  "PDU|PDU 5|Q20": ["Cabin G-04",16],
  "PDU|PDU 5|Q21": ["Cabin G-05",16],
  "PDU|PDU 5|Q22": ["Cabin G-08",16],
  "PDU|PDU 5|Q23": ["Cabin G-09",16],
  "PDU|PDU 5|Q24": ["Cabin G-10",16],
  "PDU|PDU 5|Q25": ["Cabin H-01",16],
  "PDU|PDU 5|Q26": ["Cabin H-02",16],
  "PDU|PDU 5|Q27": ["Cabin H-03",16],
  "PDU|PDU 5|Q28": ["SPARE Cabin H-03",16],
  "PDU|PDU 5|Q29": ["Cabin H-04",16],
  "PDU|PDU 5|Q30": ["SPARE Cabin H-05",16],
  "PDU|PDU 5|Q31": ["SPARE Cabin H-05",16],
  "PDU|PDU 5|Q32": ["Cabin H-06",25],
  "PDU|PDU 5|Q33": ["SPARE Cabin H-08",25],
  "PDU|PDU 5|Q34": ["Cabin H-09",25],
  "PDU|PDU 5|Q35": ["Cabin H-10",25],
  "PDU|PDU 5|Q36": ["SPARE Cabin I-05",25],
  "PDU|PDU 5|Q37": ["SPARE Cabin I-05",25],
  "PDU|PDU 5|Q38": ["SPARE Cabin I-06",25],
  "PDU|PDU 5|Q39": ["SPARE Cabin I-06",25],
  "PDU|PDU 5|Q40": ["SPARE",25],
  "PDU|PDU 5|Q41": ["Cabin G-02",25],
  "PDU|PDU 5|Q42": ["Cabin G-01",25],
  "PDU|PDU 5|Q43": ["SPARE IND. SOCKET",16],
  "PDU|PDU 5|Q44": ["SPARE IND. SOCKET",16],
  "PDU|PDU 5|Q45": ["SPARE IND. SOCKET",16],
  "PDU|PDU 5|Q46": ["SPARE IND. SOCKET",16],
  "PDU|PDU 5|Q47": ["SPARE IND. SOCKET",16],
  "PDU|PDU 5|Q48": ["Cabin G-10 SPARE",16],
  "PDU|PDU 5|Q49": ["Cabin H-11",16],
  "PDU|PDU 5|Q50": ["Cabin H-11 SPARE",16],
  "PDU|PDU 5|Q51": ["SPARE",16],
  "PDU|PDU 5|Q52": ["SPARE",16],
  "PDU|PDU 5|Q53": ["SPARE",16],
  "PDU|PDU 5|Q54": ["SPARE",16],
  "PDU|PDU 5|Q55": ["SPARE",16],
  "PDU|PDU 5|Q56": ["SPARE",16],
  "PDU|PDU 5|Q57": ["SPARE",16],
  "PDU|PDU 5|Q58": ["SPARE",16],
  "PDU|PDU 5|Q59": ["SPARE",16],
  "PDU|PDU 5|Q60": ["SPARE",16],
  "PDU|PDU 5|Q61": ["SPARE",16],
  "PDU|PDU 5|Q62": ["SPARE",16],
  "PDU|PDU 5|Q63": ["SPARE",16],
  "PDU|PDU 5|Q64": ["Cabin H-12 SPARE",16],
  "PDU|PDU 5|Q65": ["SPARE",16],
  "PDU|PDU 5|Q66": ["SPARE",16],
  "PDU|PDU 5|Q67": ["SPARE",16],
  "PDU|PDU 5|Q68": ["SPARE",16],
  "PDU|PDU 5|Q69": ["SPARE",25],
  "PDU|PDU 5|Q70": ["SPARE",25],
  "PDU|PDU 5|Q71": ["SPARE",25],
  "PDU|PDU 5|Q72": ["SPARE",25],
  "PDU|PDU 5|Q73": ["SPARE",25],
  "PDU|PDU 5|Q74": ["SPARE",25],
  "PDU|PDU 5|Q75": ["SPARE",25],
  "PDU|PDU 5|Q76": ["SPARE",25],
  "PDU|PDU 5|Q77": ["SPARE",25],
  "PDU|PDU 5|Q78": ["Cabin G-01",25],
  "PDU|PDU 7|Q1": ["Cabin M-01",20],
  "PDU|PDU 7|Q2": ["Cabin M-02",20],
  "PDU|PDU 7|Q3": ["Cabin M-03",20],
  "PDU|PDU 7|Q4": ["Cabin M-04",20],
  "PDU|PDU 7|Q5": ["Cabin M-05",20],
  "PDU|PDU 7|Q6": ["Cabin M-06",20],
  "PDU|PDU 7|Q7": ["Cabin M-07",20],
  "PDU|PDU 7|Q8": ["SPARE",20],
  "PDU|PDU 7|Q9": ["SPARE",32],
  "PDU|PDU 7|Q10": ["Cabin M-08",20],
  "PDU|PDU 7|Q11": ["Cabin M-09",20],
  "PDU|PDU 7|Q12": ["Cabin M-10",20],
  "PDU|PDU 7|Q13": ["Cabin M-11",20],
  "PDU|PDU 7|Q14": ["Cabin M-12 SPARE",20],
  "PDU|PDU 7|Q15": ["Cabin M-13",32],
  "PDU|PDU 7|Q16": ["Cabin M-15",20],
  "PDU|PDU 7|Q17": ["SPARE",32],
  "PDU|PDU 7|Q18": ["SPARE",32],
  "PDU|PDU 7|Q19": ["Cabin M-16",20],
  "PDU|PDU 7|Q20": ["L-01",20],
  "PDU|PDU 7|Q21": ["L-02",20],
  "PDU|PDU 7|Q22": ["L-03",20],
  "PDU|PDU 7|Q23": ["L-04",20],
  "PDU|PDU 7|Q24": ["L-05",20],
  "PDU|PDU 7|Q25": ["L-06",20],
  "PDU|PDU 7|Q26": ["L-07",20],
  "PDU|PDU 7|Q27": ["L-08",20],
  "PDU|PDU 7|Q28": ["L-09",20],
  "PDU|PDU 7|Q29": ["L-10",20],
  "PDU|PDU 7|Q30": ["SPARE",32],
  "PDU|PDU 7|Q31": ["SPARE",32],
  "PDU|PDU 7|Q32": ["SPARE",32],
  "PDU|PDU 7|Q33": ["SPARE",32],
  "PDU|PDU 7|Q34": ["L-11",20],
  "PDU|PDU 7|Q35": ["L-12",20],
  "PDU|PDU 7|Q36": ["L-13",20],
  "PDU|PDU 7|Q37": ["SPARE",20],
  "PDU|PDU 7|Q38": ["L-15",20],
  "PDU|PDU 7|Q39": ["L-16",20],
  "PDU|PDU 7|Q40": ["L-17",20],
  "PDU|PDU 7|Q41": ["L-18",20],
  "PDU|PDU 7|Q42": ["L-19",20],
  "PDU|PDU 7|Q43": ["SPARE",20],
  "PDU|PDU 7|Q44": ["L-14",32],
  "PDU|PDU 7|Q45": ["SPARE",32],
  "PDU|PDU 7|Q46": ["SPARE",32],
  "PDU|PDU 7|Q47": ["SPARE",32],
  "PDU|PDU 7|Q48": ["SPARE",32],
  "PDU|PDU 6|Q1": ["Cabin A-01",25],
  "PDU|PDU 6|Q2": ["Cabin A-02",25],
  "PDU|PDU 6|Q3": ["Cabin A-03",25],
  "PDU|PDU 6|Q4": ["Cabin A-04",25],
  "PDU|PDU 6|Q5": ["SPARE",25],
  "PDU|PDU 6|Q6": ["SPARE",20],
  "PDU|PDU 6|Q7": ["Cabin A-07",25],
  "PDU|PDU 6|Q8": ["Cabin A-08",25],
  "PDU|PDU 6|Q9": ["Cabin A-08",25],
  "PDU|PDU 6|Q10": ["Cabin A-09",25],
  "PDU|PDU 6|Q11": ["Cabin A-09",25],
  "PDU|PDU 6|Q12": ["Cabin A-10",25],
  "PDU|PDU 6|Q13": ["Cabin A-10",25],
  "PDU|PDU 6|Q14": ["Cabin B-02",25],
  "PDU|PDU 6|Q15": ["Cabin B-02",25],
  "PDU|PDU 6|Q16": ["Cabin B-03",25],
  "PDU|PDU 6|Q17": ["Cabin B-03",25],
  "PDU|PDU 6|Q18": ["Cabin B-04",32],
  "PDU|PDU 6|Q19": ["SPARE",32],
  "PDU|PDU 6|Q20": ["Cabin B-06",32],
  "PDU|PDU 6|Q21": ["Cabin B-07",32],
  "PDU|PDU 6|Q22": ["Cabin B-09",25],
  "PDU|PDU 6|Q23": ["Cabin B-09",25],
  "PDU|PDU 6|Q24": ["Cabin B-05",32],
  "PDU|PDU 6|Q25": ["Cabin B-05",32],
  "PDU|PDU 6|Q26": ["Cabin A-14",32],
  "PDU|PDU 6|Q27": ["Cabin A-14",32],
  "PDU|PDU 6|Q28": ["SPARE",32],
  "PDU|PDU 6|Q29": ["SPARE",32],
  "PDU|PDU 6|Q30": ["SPARE",32],
  "PDU|PDU 6|Q31": ["SPARE",16],
  "PDU|PDU 6|Q32": ["SPARE",16],
  "PDU|PDU 6|Q33": ["SPARE",25],
  "PDU|PDU 6|Q34": ["SPARE",16],
  "PDU|PDU 6|Q35": ["SPARE",16],
  "PDU|PDU 6|Q36": ["SPARE",25],
  "PDU|PDU 6|Q37": ["SPARE",16],
  "PDU|PDU 6|Q38": ["SPARE",16],
  "PDU|PDU 6|Q39": ["SPARE",25],
  "PDU|PDU 6|Q40": ["SPARE",16],
  "PDU|PDU 6|Q41": ["SPARE",16],
  "PDU|PDU 6|Q42": ["SPARE",25],
  "PDU|PDU 6|Q43": ["Cabin K-05",25],
  "PDU|PDU 6|Q44": ["Cabin K-06",25],
  "PDU|PDU 6|Q45": ["Cabin K-06",25],
  "PDU|PDU 6|Q46": ["SPARE IND. SOCKET",25],
  "PDU|PDU 6|Q47": ["SPARE IND. SOCKET",25],
  "PDU|PDU 6|Q48": ["SPARE IND. SOCKET",25],
  "PDU|PDU 6|Q49": ["SPARE IND. SOCKET",25],
  "PDU|PDU 6|Q50": ["SPARE IND. SOCKET",25],
  "PDU|PDU 6|Q51": ["Cabin A05 SPARE",25],
  "PDU|PDU 6|Q52": ["Cabin A05",25],
  "PDU|PDU 6|Q53": ["Cabin A06",25],
  "PDU|PDU 6|Q54": ["Cabin A06",25],
  "PDU|PDU 6|Q55": ["SPARE",25],
  "PDU|PDU 6|Q56": ["SPARE",25],
  "PDU|PDU 6|Q57": ["SPARE",16],
  "PDU|PDU 6|Q58": ["SPARE",16],
  "PDU|PDU 6|Q59": ["SPARE",25],
  "PDU|PDU 6|Q60": ["SPARE",25],
  "PDU|PDU 6|Q61": ["SPARE",25],
  "PDU|PDU 6|Q62": ["SPARE",25],
  "PDU|PDU 6|Q63": ["SPARE",25],
  "PDU|PDU 6|Q64": ["SPARE",16],
  "PDU|PDU 6|Q65": ["SPARE",16],
  "PDU|PDU 6|Q66": ["SPARE",16],
  "PDU|PDU 6|Q67": ["SPARE",16],
  "PDU|PDU 6|Q68": ["SPARE",16],
  "PDU|PDU 6|Q69": ["SPARE",16],
  "PDU|PDU 6|Q70": ["SPARE",16],
  "PDU|PDU 6|Q71": ["SPARE",16],
  "PDU|PDU 6|Q72": ["SPARE",16],
  "PDU|PDU 6|Q73": ["SPARE",16],
  "PDU|PDU 6|Q74": ["Cabin A11",25],
  "PDU|PDU 6|Q75": ["SPARE",16],
  "PDU|PDU 6|Q76": ["Cabin A12",25],
  "PDU|PDU 6|Q77": ["Cabin A13",16],
  "PDU|PDU 6|Q78": ["SPARE",16],
  "PDU|PDU 2|Q1": ["SPARE Cabin C-03",32],
  "PDU|PDU 2|Q2": ["SPARE Cabin C-03",32],
  "PDU|PDU 2|Q3": ["SPARE Cabin C-03",32],
  "PDU|PDU 2|Q4": ["Cabin C-04",32],
  "PDU|PDU 2|Q5": ["SPARE",32],
  "PDU|PDU 2|Q6": ["SPARE",32],
  "PDU|PDU 2|Q7": ["Cabin C-02",32],
  "PDU|PDU 2|Q8": ["Cabin C-05",32],
  "PDU|PDU 2|Q9": ["Cabin C-05",32],
  "PDU|PDU 2|Q10": ["Cabin C-07",32],
  "PDU|PDU 2|Q11": ["SPARE Cabin C-07",32],
  "PDU|PDU 2|Q12": ["Cabin C-08",32],
  "PDU|PDU 2|Q13": ["Cabin C-09",32],
  "PDU|PDU 2|Q14": ["Cabin C-09",32],
  "PDU|PDU 2|Q15": ["Cabin C-10",32],
  "PDU|PDU 2|Q16": ["Cabin C-11",32],
  "PDU|PDU 2|Q17": ["Cabin C-12",32],
  "PDU|PDU 2|Q18": ["Cabin D-02",32],
  "PDU|PDU 2|Q19": ["Cabin D-03",32],
  "PDU|PDU 2|Q20": ["Cabin D-04",32],
  "PDU|PDU 2|Q21": ["Cabin D-04",32],
  "PDU|PDU 2|Q22": ["Cabin D-05",32],
  "PDU|PDU 2|Q23": ["Cabin D-06",32],
  "PDU|PDU 2|Q24": ["Cabin D-06",32],
  "PDU|PDU 2|Q25": ["Cabin D-06A",32],
  "PDU|PDU 2|Q26": ["Cabin D-07",32],
  "PDU|PDU 2|Q27": ["Cabin D-08",32],
  "PDU|PDU 2|Q28": ["Cabin D-09",32],
  "PDU|PDU 2|Q29": ["Cabin D-10",32],
  "PDU|PDU 2|Q30": ["Cabin D-11",32],
  "PDU|PDU 2|Q31": ["Cabin D-11",32],
  "PDU|PDU 2|Q32": ["Cabin D-12",32],
  "PDU|PDU 2|Q33": ["Cabin D-12",32],
  "PDU|PDU 2|Q34": ["Cabin D-13",32],
  "PDU|PDU 2|Q35": ["Cabin D-14",32],
  "PDU|PDU 2|Q36": ["Cabin E-01",32],
  "PDU|PDU 2|Q37": ["Cabin E-06",32],
  "PDU|PDU 2|Q38": ["Cabin E-07",32],
  "PDU|PDU 2|Q39": ["Cabin E-09",32],
  "PDU|PDU 2|Q40": ["Cabin E-10",32],
  "PDU|PDU 2|Q41": ["Cabin E-11",32],
  "PDU|PDU 2|Q42": ["SPARE Cabin E-12",32],
  "PDU|PDU 2|Q43": ["SPARE",32],
  "PDU|PDU 2|Q44": ["SPARE",32],
  "PDU|PDU 2|Q45": ["SPARE",32],
  "PDU|PDU 2|Q46": ["SPARE",32],
  "PDU|PDU 2|Q47": ["SPARE",32],
  "PDU|PDU 2|Q48": ["SPARE",32],
  "PDU|PDU 2|Q49": ["Cabin C-13",32],
  "PDU|PDU 2|Q50": ["Cabin C-14",32],
  "PDU|PDU 2|Q51": ["Cabin B-10",32],
  "PDU|PDU 2|Q52": ["Cabin B-11",32],
  "PDU|PDU 2|Q53": ["Cabin B-12",32],
  "PDU|PDU 2|Q54": ["Cabin B-13",32],
  "PDU|PDU 2|Q55": ["Cabin B-14",32],
  "PDU|PDU 2|Q56": ["SPARE",32],
  "PDU|PDU 2|Q57": ["SPARE",32],
  "PDU|PDU 2|Q58": ["SPARE",32],
  "PDU|PDU 2|Q59": ["SPARE",32],
  "PDU|PDU 2|Q60": ["SPARE",32],
  "PDU|PDU 2|Q61": ["SPARE",32],
  "PDU|PDU 2|Q62": ["SPARE",32],
  "PDU|PDU 2|Q63": ["SPARE",32],
  "PDU|PDU 2|Q64": ["Cabin E-13",32],
  "PDU|PDU 2|Q65": ["SPARE",32],
  "PDU|PDU 2|Q66": ["SPARE",32],
  "PDU|PDU 2|Q67": ["SPARE",32],
  "PDU|PDU 2|Q68": ["SPARE",32],
  "PDU|PDU 2|Q69": ["SPARE",32],
  "PDU|PDU 2|Q70": ["SPARE",32],
  "PDU|PDU 2|Q71": ["SPARE",32],
  "PDU|PDU 2|Q72": ["SPARE",32],
  "PDU|PDU 2|Q73": ["SPARE",32],
  "PDU|PDU 2|Q74": ["SPARE",32],
  "PDU|PDU 2|Q75": ["SPARE",32],
  "PDU|PDU 2|Q76": ["SPARE",32],
  "PDU|PDU 2|Q77": ["SPARE",32],
  "PDU|PDU 2|Q78": ["SPARE",32],
  "PDU|PDU 4|Q1": ["SPARE",20],
  "PDU|PDU 4|Q2": ["SPARE",20],
  "PDU|PDU 4|Q3": ["SPARE",25],
  "PDU|PDU 4|Q4": ["SPARE",20],
  "PDU|PDU 4|Q5": ["Cabin H-12",25],
  "PDU|PDU 4|Q6": ["SPARE",25],
  "PDU|PDU 4|Q7": ["Cabin F-01",25],
  "PDU|PDU 4|Q8": ["SPARE Cabin F-01",25],
  "PDU|PDU 4|Q9": ["Cabin F-02",25],
  "PDU|PDU 4|Q10": ["Cabin F-03",25],
  "PDU|PDU 4|Q11": ["Cabin F-04",25],
  "PDU|PDU 4|Q12": ["Cabin F-05",25],
  "PDU|PDU 4|Q13": ["Cabin F-06",25],
  "PDU|PDU 4|Q14": ["Cabin F-03",25],
  "PDU|PDU 4|Q15": ["Cabin F-07",25],
  "PDU|PDU 4|Q16": ["Cabin F-09",25],
  "PDU|PDU 4|Q17": ["Cabin G-01",25],
  "PDU|PDU 4|Q18": ["Cabin G-02",25],
  "PDU|PDU 4|Q19": ["Cabin G-03",25],
  "PDU|PDU 4|Q20": ["Cabin G-04",25],
  "PDU|PDU 4|Q21": ["Cabin G-05",25],
  "PDU|PDU 4|Q22": ["Cabin G-08",25],
  "PDU|PDU 4|Q23": ["Cabin G-09",25],
  "PDU|PDU 4|Q24": ["Cabin G-10",25],
  "PDU|PDU 4|Q25": ["Cabin H-01",25],
  "PDU|PDU 4|Q26": ["Cabin H-02",25],
  "PDU|PDU 4|Q27": ["Cabin H-03",25],
  "PDU|PDU 4|Q28": ["SPARE Cabin H-03",16],
  "PDU|PDU 4|Q29": ["Cabin H-04",16],
  "PDU|PDU 4|Q30": ["SPARE Cabin H-05",16],
  "PDU|PDU 4|Q31": ["SPARE Cabin H-05",16],
  "PDU|PDU 4|Q32": ["Cabin H-06",16],
  "PDU|PDU 4|Q33": ["SPARE Cabin H-08",16],
  "PDU|PDU 4|Q34": ["Cabin H-09",16],
  "PDU|PDU 4|Q35": ["Cabin H-10",16],
  "PDU|PDU 4|Q36": ["SPARE Cabin I-05",16],
  "PDU|PDU 4|Q37": ["SPARE Cabin I-05",16],
  "PDU|PDU 4|Q38": ["SPARE Cabin I-06",16],
  "PDU|PDU 4|Q39": ["SPARE Cabin I-06",16],
  "PDU|PDU 4|Q40": ["SPARE",16],
  "PDU|PDU 4|Q41": ["Cabin G-02",25],
  "PDU|PDU 4|Q42": ["Cabin G-01",16],
  "PDU|PDU 4|Q43": ["SPARE IND. SOCKET",25],
  "PDU|PDU 4|Q44": ["SPARE IND. SOCKET",25],
  "PDU|PDU 4|Q45": ["SPARE IND. SOCKET",25],
  "PDU|PDU 4|Q46": ["SPARE IND. SOCKET",25],
  "PDU|PDU 4|Q47": ["SPARE IND. SOCKET",25],
  "PDU|PDU 4|Q48": ["Cabin G-10 SPARE",25],
  "PDU|PDU 4|Q49": ["Cabin H-11",25],
  "PDU|PDU 4|Q50": ["Cabin H-11 SPARE",25],
  "PDU|PDU 4|Q51": ["SPARE",25],
  "PDU|PDU 4|Q52": ["SPARE",25],
  "PDU|PDU 4|Q53": ["SPARE",25],
  "PDU|PDU 4|Q54": ["SPARE",25],
  "PDU|PDU 4|Q55": ["SPARE",25],
  "PDU|PDU 4|Q56": ["SPARE",25],
  "PDU|PDU 4|Q57": ["SPARE",25],
  "PDU|PDU 4|Q58": ["SPARE",25],
  "PDU|PDU 4|Q59": ["SPARE",25],
  "PDU|PDU 4|Q60": ["SPARE",25],
  "PDU|PDU 4|Q61": ["SPARE",25],
  "PDU|PDU 4|Q62": ["SPARE",25],
  "PDU|PDU 4|Q63": ["SPARE",25],
  "PDU|PDU 4|Q64": ["Cabin H-12 SPARE",16],
  "PDU|PDU 4|Q65": ["SPARE",16],
  "PDU|PDU 4|Q66": ["SPARE",16],
  "PDU|PDU 4|Q67": ["SPARE",16],
  "PDU|PDU 4|Q68": ["SPARE",16],
  "PDU|PDU 4|Q69": ["SPARE",16],
  "PDU|PDU 4|Q70": ["SPARE",16],
  "PDU|PDU 4|Q71": ["SPARE",16],
  "PDU|PDU 4|Q72": ["SPARE",16],
  "PDU|PDU 4|Q73": ["SPARE",16],
  "PDU|PDU 4|Q74": ["SPARE",16],
  "PDU|PDU 4|Q75": ["SPARE",16],
  "PDU|PDU 4|Q76": ["SPARE",16],
  "PDU|PDU 4|Q77": ["Cabin G-02",16],
  "PDU|PDU 4|Q78": ["SPARE",16],
  "PDU|PDU 8|Q1": ["Cabin M-01",20],
  "PDU|PDU 8|Q2": ["Cabin M-02",20],
  "PDU|PDU 8|Q3": ["Cabin M-03",20],
  "PDU|PDU 8|Q4": ["Cabin M-04",20],
  "PDU|PDU 8|Q5": ["Cabin M-05",20],
  "PDU|PDU 8|Q6": ["Cabin M-06",20],
  "PDU|PDU 8|Q7": ["Cabin M-07",20],
  "PDU|PDU 8|Q8": ["SPARE",32],
  "PDU|PDU 8|Q9": ["SPARE",32],
  "PDU|PDU 8|Q10": ["Cabin M-08",20],
  "PDU|PDU 8|Q11": ["Cabin M-09",20],
  "PDU|PDU 8|Q12": ["Cabin M-10",20],
  "PDU|PDU 8|Q13": ["Cabin M-11",20],
  "PDU|PDU 8|Q14": ["Cabin M-12 SPARE",20],
  "PDU|PDU 8|Q15": ["Cabin M-13",32],
  "PDU|PDU 8|Q16": ["Cabin M-15",20],
  "PDU|PDU 8|Q17": ["SPARE",32],
  "PDU|PDU 8|Q18": ["SPARE",32],
  "PDU|PDU 8|Q19": ["Cabin M-16",20],
  "PDU|PDU 8|Q20": ["L-01",20],
  "PDU|PDU 8|Q21": ["L-02",20],
  "PDU|PDU 8|Q22": ["L-03",20],
  "PDU|PDU 8|Q23": ["L-04",20],
  "PDU|PDU 8|Q24": ["L-05",20],
  "PDU|PDU 8|Q25": ["L-06",20],
  "PDU|PDU 8|Q26": ["L-07",20],
  "PDU|PDU 8|Q27": ["L-08",20],
  "PDU|PDU 8|Q28": ["L-09",20],
  "PDU|PDU 8|Q29": ["L-10",20],
  "PDU|PDU 8|Q30": ["SPARE",32],
  "PDU|PDU 8|Q31": ["SPARE",32],
  "PDU|PDU 8|Q32": ["SPARE",32],
  "PDU|PDU 8|Q33": ["SPARE",32],
  "PDU|PDU 8|Q34": ["L-11",20],
  "PDU|PDU 8|Q35": ["L-12",20],
  "PDU|PDU 8|Q36": ["L-13",20],
  "PDU|PDU 8|Q37": ["SPARE",20],
  "PDU|PDU 8|Q38": ["L-15",20],
  "PDU|PDU 8|Q39": ["L-16",20],
  "PDU|PDU 8|Q40": ["L-17",20],
  "PDU|PDU 8|Q41": ["L-18",20],
  "PDU|PDU 8|Q42": ["L-19",20],
  "PDU|PDU 8|Q43": ["SPARE",20],
  "PDU|PDU 8|Q44": ["L-14",32],
  "PDU|PDU 8|Q45": ["SPARE",32],
  "PDU|PDU 8|Q46": ["SPARE",32],
  "PDU|PDU 8|Q47": ["SPARE",32],
  "PDU|PDU 8|Q48": ["SPARE",32]
};
/* @@ALLOWLIST-END */


function doPost(e) {
  try {
    if (!e || !e.postData || !e.postData.contents) {
      return json({ result: 'error', message: 'Empty request' });
    }

    var payload = JSON.parse(e.postData.contents);
    if (!payload || typeof payload !== 'object') {
      return json({ result: 'error', message: 'Malformed request' });
    }

    /* Only these three do anything. Anything else used to fall through to
       the write path - a request with no type at all would have written. */
    if (payload.type === 'status')       return handleStatus(payload);
    if (payload.type === 'history')      return handleHistory(payload);
    if (payload.type === 'load-reading') return handleSubmit(payload);
    return json({ result: 'error', message: 'Unknown request type' });

  } catch (err) {
    return json({ result: 'error', message: String(err) });
  }
}


/** Health check: opening the /exec URL in a browser should show this. */
function doGet() {
  return json({
    result: 'success',
    service: 'KOC Data Center load reading',
    sheet: SHEET_NAME,
    rows: Math.max(0, getSheet().getLastRow() - 1)
  });
}


/* =========================================================================
   status - what is already recorded for a given date
   ========================================================================= */

function handleStatus(payload) {
  var date = String(payload.date || '').trim();
  if (!date) return json({ result: 'error', message: 'No date given' });

  var index = readIndex(date);
  var recorded = {};

  for (var key in index) {
    var hit = index[key];
    recorded[key] = { r: hit.r, y: hit.y, b: hit.b, row: hit.row };
  }

  LAST_SCAN_DATES_.sort();
  LAST_SCAN_DATES_.reverse();

  return json({ result: 'success', date: date, recorded: recorded,
                latest: LAST_SCAN_LATEST_,
                dates: LAST_SCAN_DATES_.slice(0, 120) });
}


/* =========================================================================
   history - how the system has actually loaded over a period

   A single day's reading can miss the annual peak entirely, so an
   additional-load study has to be judged against the worst condition
   actually recorded, not against whatever today happened to be.

   Returns, for a date range:
     stats   per feeder - max, min, mean, median, count, and the DATE the
             maximum was recorded, so a peak can be traced back
     demand  the site demand, computed as the COINCIDENT sum of the two
             incomers on the same date. Taking max(A) + max(B) across
             different dates would invent a peak that never happened.
     cover   what the range really holds: first and last date found and
             how many distinct reading dates. The client needs this to say
             whether the requested period is actually covered.
   ========================================================================= */

function handleHistory(payload) {
  var from = normaliseDate(payload.from || '');
  var to = normaliseDate(payload.to || '');
  if (!from || !to) return json({ result: 'error', message: 'from and to dates are required' });

  var sheet = getSheet();
  var last = sheet.getLastRow();
  if (last < 2) {
    return json({ result: 'success', from: from, to: to,
                  cover: { dates: 0, first: null, last: null, rows: 0 },
                  stats: {}, demand: null });
  }

  var width = C_B - C_DATE + 1;
  var data = sheet.getRange(2, C_DATE, last - 1, width).getValues();

  var vals = {};          /* key -> [ {v, d} ] */
  var perDate = {};       /* date -> { 'Incomer A': v, 'Incomer B': v } */
  var seenDates = {};
  var rows = 0, first = null, lastSeen = null;

  for (var i = 0; i < data.length; i++) {
    var row = data[i];
    var d = normaliseDate(row[0]);
    if (!d || d < from || d > to) continue;

    rows++;
    seenDates[d] = true;
    if (!first || d < first) first = d;
    if (!lastSeen || d > lastSeen) lastSeen = d;

    var key = rowKey(row[C_CATEGORY - C_DATE],
                     row[C_EQUIPMENT - C_DATE],
                     row[C_CIRCUIT - C_DATE]);

    var r = Number(row[C_R - C_DATE]) || 0;
    var y = Number(row[C_Y - C_DATE]) || 0;
    var b = Number(row[C_B - C_DATE]) || 0;
    var v = Math.max(r, y, b);

    var ph = (v === r) ? 'R' : (v === y) ? 'Y' : 'B';
    if (!vals[key]) vals[key] = [];
    vals[key].push({ v: v, d: d, ph: ph });

    var eq = String(row[C_EQUIPMENT - C_DATE]).trim();
    if (eq === 'Incomer A' || eq === 'Incomer B') {
      if (!perDate[d]) perDate[d] = {};
      /* keep each phase separately: the transformer carries the sum of the
         two incomers PHASE BY PHASE, and summing the two maxima instead
         would invent a current that no conductor ever saw */
      var cur = perDate[d][eq] || { r: 0, y: 0, b: 0 };
      perDate[d][eq] = { r: Math.max(cur.r, r), y: Math.max(cur.y, y), b: Math.max(cur.b, b) };
    }
  }

  /* per feeder statistics */
  var stats = {};
  for (var k in vals) {
    var arr = vals[k];
    var nums = arr.map(function (x) { return x.v; }).sort(function (a, b) { return a - b; });
    var sum = 0;
    for (var j = 0; j < nums.length; j++) sum += nums[j];
    var top = arr[0];
    for (var m = 1; m < arr.length; m++) if (arr[m].v > top.v) top = arr[m];

    stats[k] = {
      n: nums.length,
      min: nums[0],
      max: nums[nums.length - 1],
      avg: sum / nums.length,
      med: median(nums),
      p95: percentile(nums, 0.95),
      maxDate: top.d,
      maxPhase: top.ph
    };
  }

  /* coincident site demand, per date */
  var demand = null;
  var dd = [];
  for (var dt in perDate) {
    var e = perDate[dt];
    /* only count a date where BOTH incomers were read, otherwise the
       total is not the site demand */
    if (e['Incomer A'] === undefined || e['Incomer B'] === undefined) continue;
    var a = e['Incomer A'], b2 = e['Incomer B'];
    var sr = a.r + b2.r, sy = a.y + b2.y, sb = a.b + b2.b;
    var sv = Math.max(sr, sy, sb);
    dd.push({ d: dt, v: sv, ph: (sv === sr) ? 'R' : (sv === sy) ? 'Y' : 'B',
              a: Math.max(a.r, a.y, a.b), b: Math.max(b2.r, b2.y, b2.b) });
  }
  if (dd.length) {
    var dv = dd.map(function (x) { return x.v; }).sort(function (a, b) { return a - b; });
    var dsum = 0;
    for (var q = 0; q < dv.length; q++) dsum += dv[q];
    var dtop = dd[0];
    for (var w = 1; w < dd.length; w++) if (dd[w].v > dtop.v) dtop = dd[w];
    demand = {
      n: dv.length, min: dv[0], max: dv[dv.length - 1],
      avg: dsum / dv.length, med: median(dv), p95: percentile(dv, 0.95),
      maxDate: dtop.d,
      maxPhase: dtop.ph,
      aAtMax: dtop.a,
      bAtMax: dtop.b,
      bothIncomersDates: dv.length
    };
  }

  var nDates = 0;
  for (var s2 in seenDates) nDates++;

  return json({
    result: 'success', from: from, to: to,
    cover: { dates: nDates, first: first, last: lastSeen, rows: rows },
    stats: stats, demand: demand
  });
}


function median(sorted) {
  if (!sorted.length) return null;
  var mid = Math.floor(sorted.length / 2);
  return sorted.length % 2 ? sorted[mid] : (sorted[mid - 1] + sorted[mid]) / 2;
}


function percentile(sorted, p) {
  if (!sorted.length) return null;
  var idx = Math.ceil(p * sorted.length) - 1;
  if (idx < 0) idx = 0;
  if (idx >= sorted.length) idx = sorted.length - 1;
  return sorted[idx];
}


/* =========================================================================
   submit
   ========================================================================= */

function handleSubmit(payload) {
  var rawMeta = (payload.meta && typeof payload.meta === 'object') ? payload.meta : {};
  var rows = Array.isArray(payload.rows) ? payload.rows : [];

  if (!rows.length) return json({ result: 'error', message: 'No readings in request' });
  if (rows.length > LIMITS.MAX_ROWS) {
    return json({ result: 'error', message: 'Too many rows in one request (' + rows.length +
                  '; the limit is ' + LIMITS.MAX_ROWS + ')' });
  }

  /* The header applies to every row, so a bad one refuses the whole request
     rather than writing rows under a date nobody meant. */
  var date = checkDate(rawMeta.date);
  if (date.error) return json({ result: 'error', message: date.error });
  var time = checkTime(rawMeta.time);
  if (time.error) return json({ result: 'error', message: time.error });

  var meta = {
    date:    date.value,
    time:    time.value,
    takenBy: safeText(rawMeta.takenBy),
    site:    safeText(rawMeta.site),
    remarks: safeText(rawMeta.remarks)
  };

  // A lock keeps two phones submitting at once from interleaving rows or
  // both getting past the duplicate check.
  var lock = LockService.getScriptLock();
  try {
    lock.waitLock(30000);
  } catch (err) {
    return json({ result: 'error', message: 'Sheet busy, try again' });
  }

  try {
    var sheet = getSheet();
    var index = readIndex(meta.date);
    var stamp = new Date();

    var saved = [];        // keys written as new rows
    var replaced = [];     // keys that overwrote an existing row
    var duplicates = [];   // keys refused
    var rejected = [];     // keys refused as invalid, with the reason
    var appendRows = [];   // values queued for one setValues call
    var appendKeys = [];
    var seen = {};         // one row per key per request

    rows.forEach(function (r) {
      if (!r || typeof r !== 'object') {
        rejected.push({ key: '', reason: 'Not a reading' });
        return;
      }
      var key = rowKey(r.category, r.equipment, r.circuit);

      /* A row is rejected on its own, not the whole request, so a stale
         allowlist - config.js edited, this file not regenerated - refuses
         the one new way and still saves the rest of the round. */
      var spec = ALLOWED[key];
      if (!spec) {
        rejected.push({ key: key, reason: 'Not a feeder or PDU way this sheet knows - if it ' +
                        'was just added to config.js, regenerate Code.gs and redeploy' });
        return;
      }
      if (seen[key]) {
        rejected.push({ key: key, reason: 'Sent twice in one request' });
        return;
      }
      seen[key] = true;

      var cur = checkCurrents(r);
      if (cur.error) {
        rejected.push({ key: key, reason: cur.error });
        return;
      }

      var values = buildRow(stamp, meta, key, spec, cur);
      var existing = index[key];

      if (existing) {
        if (!r.replace) {
          duplicates.push({ key: key, r: existing.r, y: existing.y, b: existing.b, row: existing.row });
          return;
        }
        /* Copy what is there before overwriting it. Without this a false
           reading written over a real one would leave no trace - so if the
           copy cannot be made, the overwrite does not happen either. */
        try {
          audit(sheet, existing.row, values, stamp);
        } catch (err) {
          rejected.push({ key: key, reason: 'Could not keep a copy of the existing reading, ' +
                          'so it was left unchanged (' + String(err) + ')' });
          return;
        }
        sheet.getRange(existing.row, 1, 1, HEADERS.length).setValues([values]);
        replaced.push({ key: key, row: existing.row });
        return;
      }

      appendRows.push(values);
      appendKeys.push(key);
    });

    if (appendRows.length) {
      var first = sheet.getLastRow() + 1;
      sheet.getRange(first, 1, appendRows.length, HEADERS.length).setValues(appendRows);
      appendKeys.forEach(function (key, i) {
        saved.push({ key: key, row: first + i });
      });
    }

    return json({
      result: 'success',
      saved: saved,
      replaced: replaced,
      duplicates: duplicates,
      rejected: rejected
    });

  } catch (err) {
    return json({ result: 'error', message: String(err) });
  } finally {
    lock.releaseLock();
  }
}


/* Everything about the equipment comes from the allowlist and everything
   derived is recomputed here. The request supplies only which row it is and
   the three currents - it cannot set a rack name, a rating or a "% loaded". */
function buildRow(stamp, meta, key, spec, cur) {
  var parts = key.split('|');
  var rack = spec[0], rated = spec[1];

  var present = [cur.r, cur.y, cur.b].filter(function (v) { return v !== ''; });
  var max = present.length ? Math.max.apply(null, present) : '';
  var pct = (max !== '' && rated) ? Math.round(max / rated * 1000) / 10 : '';

  return [
    stamp,
    meta.date,
    meta.time,
    meta.takenBy,
    meta.site,
    parts[0],
    parts[1],
    parts[2],
    rack,
    rated === '' ? '' : rated,
    cur.r,
    cur.y,
    cur.b,
    max,
    pct,
    nemaUnbalance(cur.r, cur.y, cur.b),
    meta.remarks
  ];
}


/* =========================================================================
   sheet access
   ========================================================================= */

/**
 * Everything already recorded on one date, keyed by category|equipment|circuit.
 * Only the columns needed for the lookup are read, so this stays cheap as the
 * sheet grows.
 */
/* The newest date seen by the last readIndex pass. It comes free - that pass
   already looks at every date - and saves reading the column a second time
   just to answer "what is the most recent day on the sheet". */
var LAST_SCAN_LATEST_ = null;

/* Every distinct date seen by that same pass, newest first. Also free - the
   page needs it to offer a list of days to look back at, and asking for it
   separately would be another round trip for something already in hand. */
var LAST_SCAN_DATES_ = [];

function readIndex(date) {
  var sheet = getSheet();
  var last = sheet.getLastRow();
  var index = {};

  /* Cleared before the early return, not after it. Leaving it set would let
     an empty sheet report the previous call's answer - which in Apps Script
     only bites when one instance serves two requests, but is wrong either
     way and is exactly what the test caught. */
  LAST_SCAN_LATEST_ = null;
  LAST_SCAN_DATES_ = [];

  if (last < 2) return index;

  var width = C_B - C_DATE + 1;                       // Date .. B
  var data = sheet.getRange(2, C_DATE, last - 1, width).getValues();
  var want = normaliseDate(date);
  var seenDates = {};

  for (var i = 0; i < data.length; i++) {
    var row = data[i];
    var d = normaliseDate(row[0]);
    if (d) {
      if (LAST_SCAN_LATEST_ === null || d > LAST_SCAN_LATEST_) LAST_SCAN_LATEST_ = d;
      if (seenDates[d] === undefined) { seenDates[d] = true; LAST_SCAN_DATES_.push(d); }
    }
    if (d !== want) continue;

    var key = rowKey(row[C_CATEGORY - C_DATE],
                     row[C_EQUIPMENT - C_DATE],
                     row[C_CIRCUIT - C_DATE]);

    // Last write wins, matching what a replace leaves behind.
    index[key] = {
      row: i + 2,
      r: row[C_R - C_DATE],
      y: row[C_Y - C_DATE],
      b: row[C_B - C_DATE]
    };
  }

  return index;
}


function getSheet() {
  var ss = SpreadsheetApp.getActiveSpreadsheet();
  var sheet = ss.getSheetByName(SHEET_NAME);

  if (!sheet) {
    sheet = ss.insertSheet(SHEET_NAME);
  }

  if (sheet.getLastRow() === 0) {
    sheet.getRange(1, 1, 1, HEADERS.length).setValues([HEADERS]);
    sheet.getRange(1, 1, 1, HEADERS.length).setFontWeight('bold');
    sheet.setFrozenRows(1);
  }

  return sheet;
}


/* =========================================================================
   helpers
   ========================================================================= */


/* =========================================================================
   Checking what a request sends. Nothing here trusts the page: the URL is
   public, so these assume the request may come from anywhere.
   ========================================================================= */

/* A reading date: yyyy-mm-dd, a real calendar day, not before FIRST_YEAR and
   not more than DAYS_AHEAD into the future. */
function checkDate(v) {
  var s = String(v === null || v === undefined ? '' : v).trim();
  var m = /^(\d{4})-(\d{2})-(\d{2})$/.exec(s);
  if (!m) return { error: 'Reading date must be yyyy-mm-dd' };

  var y = +m[1], mo = +m[2], d = +m[3];
  var dt = new Date(Date.UTC(y, mo - 1, d));
  if (dt.getUTCFullYear() !== y || dt.getUTCMonth() !== mo - 1 || dt.getUTCDate() !== d) {
    return { error: 'Reading date ' + s + ' is not a real date' };
  }
  if (y < LIMITS.FIRST_YEAR) return { error: 'Reading date ' + s + ' is too early' };

  var limit = Utilities.formatDate(new Date(Date.now() + LIMITS.DAYS_AHEAD * 86400000),
                                   sheetTz_(), 'yyyy-MM-dd');
  if (s > limit) return { error: 'Reading date ' + s + ' is in the future' };

  return { value: s };
}

/* Time of reading: blank, or hh:mm on a 24-hour clock. */
function checkTime(v) {
  var s = String(v === null || v === undefined ? '' : v).trim();
  if (s === '') return { value: '' };
  var m = /^([01]\d|2[0-3]):([0-5]\d)$/.exec(s);
  if (!m) return { error: 'Time must be hh:mm' };
  return { value: s };
}

/* The three phase currents. Each is blank or a number from 0 to MAX_AMPS,
   and at least one must be present. Not checked against the feeder's rating
   on purpose - see LIMITS. */
function checkCurrents(r) {
  var out = {};
  var any = false;
  var names = { r: 'R', y: 'Y', b: 'B' };
  for (var ph in names) {
    var v = r[ph];
    if (v === '' || v === null || v === undefined) { out[ph] = ''; continue; }
    var n = (typeof v === 'number') ? v : Number(String(v).trim());
    if (typeof v !== 'number' && !/^-?\d+(\.\d+)?$/.test(String(v).trim())) {
      return { error: names[ph] + ' phase is not a number' };
    }
    if (!isFinite(n)) return { error: names[ph] + ' phase is not a number' };
    if (n < 0)        return { error: names[ph] + ' phase is negative' };
    if (n > LIMITS.MAX_AMPS) {
      return { error: names[ph] + ' phase ' + n + ' A is beyond anything on this site' };
    }
    out[ph] = n;
    any = true;
  }
  if (!any) return { error: 'No current entered' };
  return out;
}

/* Free text: trimmed, stripped of control characters, capped, and never
   allowed to begin a formula.

   Sheets turns a value starting with = + - or @ into a formula, and a formula
   such as IMPORTXML or HYPERLINK can send the sheet's contents to another
   server whenever anyone opens it. A leading apostrophe makes Sheets store it
   as plain text; it is not shown in the cell. */
function safeText(v) {
  var s = String(v === null || v === undefined ? '' : v);
  s = s.replace(/[\u0000-\u001F\u007F]/g, ' ').replace(/\s+/g, ' ').trim();
  if (s.length > LIMITS.MAX_TEXT) s = s.slice(0, LIMITS.MAX_TEXT);
  if (/^[=+\-@]/.test(s)) s = "'" + s;
  return s;
}

/* Greatest deviation from the mean, as a percentage of it - the same NEMA
   form load-reading.js shows, to one decimal. Blank unless all three phases
   are present, which is how single-phase ways come out blank. */
function nemaUnbalance(r, y, b) {
  if (r === '' || y === '' || b === '') return '';
  var avg = (r + y + b) / 3;
  if (avg <= 0) return '';
  var dev = Math.max(Math.abs(r - avg), Math.abs(y - avg), Math.abs(b - avg));
  return Math.round(dev / avg * 1000) / 10;
}

/* Before a row is overwritten, keep both versions side by side on the Audit
   tab: what was there, then what replaced it. Throws if it cannot, and the
   caller then leaves the reading unchanged. */
function audit(sheet, rowNum, newValues, stamp) {
  var old = sheet.getRange(rowNum, 1, 1, HEADERS.length).getValues()[0];
  var a = getAuditSheet();
  var first = a.getLastRow() + 1;
  a.getRange(first, 1, 2, HEADERS.length + 3).setValues([
    [stamp, rowNum, 'before'].concat(old),
    [stamp, rowNum, 'after'].concat(newValues)
  ]);
}

function getAuditSheet() {
  var ss = SpreadsheetApp.getActiveSpreadsheet();
  var a = ss.getSheetByName(AUDIT_SHEET);
  if (!a) {
    a = ss.insertSheet(AUDIT_SHEET);
    a.getRange(1, 1, 1, HEADERS.length + 3)
     .setValues([['Audited at', 'Sheet row', 'Version'].concat(HEADERS)]);
    a.setFrozenRows(1);
  }
  return a;
}

function rowKey(category, equipment, circuit) {
  return [String(category === undefined || category === null ? '' : category).trim(),
          String(equipment === undefined || equipment === null ? '' : equipment).trim(),
          String(circuit   === undefined || circuit   === null ? '' : circuit).trim()
         ].join('|');
}


/**
 * Sheets may store the date column as text or coerce it to a Date, depending
 * on the cell format. Reduce either to yyyy-MM-dd so the comparison holds.
 */
/* Both of the calls this used to make per row - getSpreadsheetTimeZone and
   formatDate - cross the Apps Script service bridge, which costs milliseconds
   each. On a sheet of 400 rows that was over 800 bridge calls for a single
   status check, and it was most of the ten seconds the page spent waiting.

   The timezone is fetched once. The formatted date is memoised on the
   timestamp, so a sheet holding five distinct dates formats five times
   instead of once per row. Both caches live only for the duration of one
   request, which is all Apps Script gives us anyway. */
var TZ_ = null;
var DATE_MEMO_ = {};

function sheetTz_() {
  if (TZ_ === null) TZ_ = SpreadsheetApp.getActiveSpreadsheet().getSpreadsheetTimeZone();
  return TZ_;
}

function normaliseDate(v) {
  if (v instanceof Date) {
    var t = v.getTime();
    var hit = DATE_MEMO_[t];
    if (hit === undefined) {
      hit = Utilities.formatDate(v, sheetTz_(), 'yyyy-MM-dd');
      DATE_MEMO_[t] = hit;
    }
    return hit;
  }
  return String(v === null || v === undefined ? '' : v).trim().slice(0, 10);
}


/** Keep genuine zeros, but write '' rather than 0 for a missing reading. */
function blankOrNum(v) {
  if (v === '' || v === null || v === undefined) return '';
  var n = Number(v);
  return isNaN(n) ? '' : n;
}


function json(obj) {
  return ContentService
    .createTextOutput(JSON.stringify(obj))
    .setMimeType(ContentService.MimeType.JSON);
}
